let obj={
  data: [{
    name:'首页',
    key:'0',
    path:'/admin/home'
  },
  {
    name:'商品管理',
    key:'1',
    path:'/admin/project/',
    children:[
      {
        name:'商品列表',
        key:'1-0',
        path:'/admin/project/projectlist',
      },
      {
        name:'商品添加',
        key:'1-1',
        path:'/admin/project/projectadd'
      }
    ]
  },
  {
    name:'用户管理',
    key:'2',
    path:'/admin/owner',
    children:[
      {
        name:'用户列表',
        key:'2-0',
        path:'/admin/owner/userlist'
      },
      {
        name:'添加用户',
        key:'2-1',
        path:'/admin/owner/useradd'
      }
    ]
  },
  {
    name:'广告位管理',
    key:'3',
    path:'/admin/banner',
    children:[
      {
        name:'广告位列表',
        key:'3-0',
        path:'/admin/banner/bannerlist'
      },
      {
        name:'添加广告位',
        key:'3-1',
        path:'/admin/banner/banneradd'
      }
    ]
  }
  ]
}
export default obj